In [1]:
from data_handler import data_wrangler

2024-08-28 13:56:33.500690: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
import numpy as np

In [3]:
x = np.array([np.nan, 2])

In [4]:
x
np.unique(x)

array([ 2., nan])

In [5]:
train_wrangler = data_wrangler("../data/ml_sets/pyramid_lf22", 18, 1, [34, 34, 34, 34, 34, 34, 34, 34, 2, 2, 2, 2, 2, 2, 1, 15, 15, 1],
                                   1000, -999, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
                                   [15, 16, 17])

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '../data/ml_sets/pyramid_lf22/layer_18.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [ ]:
train_wrangler.set_mode("train")
train_wrangler.set_fold(0)

In [ ]:
print("len", len(train_wrangler))
print(train_wrangler[0][0][17][0])
print("***")
print(train_wrangler[0][1][2][0])
print(type(train_wrangler[0][1][2][0]))

###
nancount = []
ndvalcount = []
oobcount = []
mins = []
maxs = []
unique = []

ynancount = []
yndvalcount = []
yoobcount = []
ymins = []
ymaxs = []
yunique = []

### iterate over batches
for i in range(len(train_wrangler)):
    xlist, ylist = train_wrangler.test_get(i)
    ### iterate over layers
    for j in range(len(xlist)):
        unique.append([])
        ### iterate over samples
        for k in range(len(xlist[j])):
            if np.isnan(xlist[j][k]).any():
                nancount.append((i, j, k))
            if -999 in xlist[j][k]:
                ndvalcount.append((i, j, k))
            if np.min(xlist[j][k]) < 0 or np.max(xlist[j][k]) > 1:
                oobcount.append((i, j, k))
                mins.append(np.min(xlist[j][k]))
                maxs.append(np.max(xlist[j][k]))
            unique[j].append(np.unique(xlist[j][k]))
    ### iterate over layers
    for j in range(len(ylist)):
        ### iterate over samples
        for k in range(len(ylist[j])):
            if np.isnan(ylist[j][k]).any():
                ynancount.append((i, j, k))
            if -999 in ylist[j][k]:
                yndvalcount.append((i, j, k))
            if np.min(ylist[j][k]) < 0 or np.max(ylist[j][k]) > 1:
                yoobcount.append((i, j, k))
                ymins.append(np.min(ylist[j][k]))
                ymaxs.append(np.max(ylist[j][k]))
            unique[j].append(np.unique(xlist[j][k]))

print("nan", len(nancount))
print("ndv", len(ndvalcount))
print("oob", len(oobcount))

len 51
[[0.92196858 0.92196858 0.92196858 ... 0.89214766 0.89214766 0.89214766]
 [0.92196858 0.92196858 0.92196858 ... 0.89214766 0.89214766 0.89214766]
 [0.92196858 0.92196858 0.92196858 ... 0.89214766 0.89214766 0.89214766]
 ...
 [0.90705806 0.90705806 0.90705806 ... 0.89960289 0.89960289 0.89960289]
 [0.90705806 0.90705806 0.90705806 ... 0.89960289 0.89960289 0.89960289]
 [0.90705806 0.90705806 0.90705806 ... 0.89960289 0.89960289 0.89960289]]
***
[[0.13233472]]
<class 'numpy.ndarray'>
nan 0
ndv 0
oob 947585


In [ ]:
amin = np.argmin(mins)
print(mins[amin])
print(oobcount[amin])
#print(maxs)

print("ynan", len(ynancount))
print("yndv", len(yndvalcount))
print("yoob", len(yoobcount))

-11.00999927520752
(17, 13, 679)
ynan 0
yndv 0
yoob 39380


In [ ]:
print(ynancount)

[]


In [ ]:
print(train_wrangler.test_get(1)[0][0][0])
-32768 in train_wrangler.test_get(1)[0][0][0]

[[2510. 2507. 2504. ... 2427. 2427. 2425.]
 [2512. 2507. 2503. ... 2429. 2429. 2426.]
 [2513. 2509. 2504. ... 2430. 2430. 2426.]
 ...
 [2334. 2337. 2350. ... 2451. 2448. 2444.]
 [2325. 2331. 2343. ... 2454. 2451. 2448.]
 [2315. 2322. 2329. ... 2454. 2452. 2452.]]


False

In [ ]:
uniquenp = []
### iterate over layers
for i in range(len(unique)):
    uniquenp.append(np.concatenate(unique[i]))
    uniquenp[i] = np.unique(uniquenp[i])


ValueError: need at least one array to concatenate